application: pypyhello
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /kreena
  script: helloworld.py
- url: /parag
  script: helloparag.py
- url: /env
  script: printenv.py
- url: /images
  static_dir: images/
- url: /lol
  script: lol.py
  secure: always